services:
  app:
    image: mysociety/2025-constituencies:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/2025_constituencies      
    volumes:
      - ./:/workspaces/2025_constituencies/