#!/bin/bash 

echo "--------------"
echo "Running pytest"
echo "--------------"
poetry run pytest
pytestexit=$?
echo "--------------"
echo "Running ruff"
echo "--------------"
poetry run ruff check .
ruffcheckexit=$?
poetry run ruff format . --check
ruffformatexit=$?

echo "Pytest status: $pytestexit"
echo "Ruff Check status: $ruffcheckexit"
echo "Ruff Format status: $ruffformatexit"

sum="$(($pytestexit + $ruffcheckexit + $ruffformatexit))"

if [ "$sum" != "0" ]; then
    exit 1
else
    exit 0
fi